/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import controller.TaskController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import model.Project;
import model.Task;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {
        
        ProjectController pjc = new ProjectController();
        Project pj = new Project();
        TaskController tkc = new TaskController();
        Task tk = new Task();
//        pj.setName("Eita");
//        pj.setDescription("Descrição");
//        pjc.save(pj);
//        
//        pj.setId(4);
//        pj.setName("Mano?");
//        pjc.update(pj);
        
//        pjc.deletById(1);

//        List<Project> projects = pjc.getAll();
//        System.out.println("Toltal de projetos = " + projects.size());

          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String data = "2003-10-02";
          tk.setId_project(1);
          tk.setName("Fazer tal");
          tk.setDescription("Sla mano");
          tk.setIsCompleted(false);
          tk.setNotes("Essa ai");
          tk.setDeadline(sdf.parse(data));
          tkc.save(tk);
          
          
          
          
        

    }
}
